apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crypto-edge-operator
spec:
  targetNamespace: crypto-edge-operator
  storageNamespace: crypto-edge-operator
  values:
    installMode:
      crdsRbacOnly: true
    serviceAccountRef:
      name: operator-cluster-oidc:system:serviceaccount:crypto-edge-operator:crypto-edge-operator
      create: false
