apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/namespaces/apisync.yaml
  - ../../../../base/namespaces/cert-manager.yaml
  - ../../../../base/namespaces/envoy-gateway-system.yaml
  - ../../../../base/namespaces/linkerd.yaml
  - ../../../../base/namespaces/services.yaml
  - ../../../../base/namespaces/storage.yaml
  - ../../../../base/namespaces/reloader.yaml
  - ../../../../base/namespaces/external-secret.yaml
  - ../../../../base/namespaces/openbao.yaml
  - ../../../../base/namespaces/kms-system.yaml
  - ../../../../base/namespaces/crypto-edge-operator.yaml
